name: "Build and deploy REST API"

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }} 
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './build/*'
          remote_path: '/var/www/vhosts/ct503823grp2-ct5038.uogs.co.uk/api.CT503823Grp2-ct5038.uogs.co.uk'
          sftp_only: true